/**
 * Typed storage items, built on WXT's storage API.
 *
 * Every key Helios persists is declared here once, with its default. Reads
 * return the default when a key is unset, so call sites don't repeat it, and
 * items expose `.watch()` for reacting to changes.
 *
 * Keys are declared as `local:<name>`, which maps to the same
 * `chrome.storage.local` key the extension has always used — existing user
 * data is read unchanged.
 */
import { storage } from 'wxt/utils/storage';

export interface HotkeyBinding {
  key: string;
  ctrl: boolean;
  shift: boolean;
  alt: boolean;
  meta?: boolean;
}

export interface VideoPlayerSettings {
  hotkeysEnabled: boolean;
  dualSubtitlesEnabled: boolean;
  secondarySubtitleLanguage: string | null;
  pauseOnHover: boolean;
  pauseAtEnd: boolean;
  autoPlayAfterNav: boolean;
  hotkeys: Record<string, HotkeyBinding>;
}

export interface ShortcutSettings {
  /**
   * Written by the settings page as `HotkeyBinding` objects; older installs
   * hold bare key strings. Readers must handle both.
   */
  popup?: Record<string, string | HotkeyBinding>;
  video?: Record<string, HotkeyBinding>;
  videoNavigation?: Record<string, HotkeyBinding>;
  [key: string]: unknown;
}

export interface AnkiSettings {
  deck?: string;
  noteType?: string;
  fieldMappings?: Record<string, string>;
  checkDuplicates?: boolean;
  allowDuplicates?: boolean;
  includeSentence?: boolean;
  tags?: string[];
  importYoungAsLearning?: boolean;
  autoSyncLearningWords?: boolean;
  [key: string]: unknown;
}

/** A subtitle track the user picked, remembered so it can be re-selected. */
export interface SubtitleTrackPreference {
  language: string;
  languageName?: string;
  isAutoGenerated?: boolean;
  url?: string;
}

/**
 * Chosen subtitle tracks. `global` maps a base language to the full code the
 * user preferred for it (e.g. `zh` → `zh-Hans`); `perVideo` is keyed by video id.
 */
export interface SubtitlePreferences {
  global: Record<string, string>;
  perVideo: Record<string, SubtitleTrackPreference>;
}

export interface VocabEntry {
  word?: string;
  character?: string;
  definition?: string;
  pinyin?: string;
  dateAdded?: string;
  reviewCount?: number;
  [key: string]: unknown;
}

/** Default video-player hotkeys, fresh each call so callers can mutate safely. */
export function defaultVideoPlayerSettings(): VideoPlayerSettings {
  return {
    hotkeysEnabled: true,
    dualSubtitlesEnabled: false,
    secondarySubtitleLanguage: null,
    pauseOnHover: true,
    pauseAtEnd: false,
    autoPlayAfterNav: false,
    hotkeys: {
      previous: { key: 'a', shift: false, ctrl: false, alt: false },
      next: { key: 'd', shift: false, ctrl: false, alt: false },
      restart: { key: 's', shift: false, ctrl: false, alt: false },
      toggle: { key: 'w', shift: false, ctrl: false, alt: false },
    },
  };
}

/**
 * Items with a `fallback` return it when unset. Items without one return
 * `null`, which is the honest answer for state that has no meaningful default
 * (a language the user hasn't chosen yet, a date nothing has stamped).
 *
 * IMPORTANT — never mutate a value returned by `getValue()` in place when the
 * item declares an object or array fallback. WXT hands back the *same* fallback
 * instance on every miss, so `(await items.vocabList.getValue()).push(x)` would
 * permanently pollute the default for every later reader. Copy first:
 * `const list = [...(await items.vocabList.getValue())]`.
 */
export const items = {
  // ---- Core state ----
  extensionEnabled: storage.defineItem<boolean>('local:extensionEnabled', { fallback: true }),
  targetLanguage: storage.defineItem<string>('local:targetLanguage'),
  nativeLanguage: storage.defineItem<string>('local:nativeLanguage', { fallback: 'en' }),
  activationKey: storage.defineItem<string>('local:activationKey', { fallback: 'Shift' }),
  autoHighlight: storage.defineItem<boolean>('local:autoHighlight', { fallback: true }),
  popupTheme: storage.defineItem<string>('local:popupTheme', { fallback: 'dark' }),

  // ---- Vocabulary ----
  vocabList: storage.defineItem<VocabEntry[]>('local:vocabList', { fallback: [] }),
  knownWords: storage.defineItem<string[]>('local:knownWords', { fallback: [] }),
  knownWordsByLanguage: storage.defineItem<Record<string, string[]>>(
    'local:knownWordsByLanguage', { fallback: {} },
  ),
  ignoredWordsByLanguage: storage.defineItem<Record<string, string[]>>(
    'local:ignoredWordsByLanguage', { fallback: {} },
  ),
  learningWordsByLanguage: storage.defineItem<Record<string, string[]>>(
    'local:learningWordsByLanguage', { fallback: {} },
  ),
  chineseExtensionKnownWords: storage.defineItem<string[]>(
    'local:chineseExtensionKnownWords', { fallback: [] },
  ),
  chineseExtensionIgnoredWords: storage.defineItem<string[]>(
    'local:chineseExtensionIgnoredWords', { fallback: [] },
  ),
  chineseExtensionVocabList: storage.defineItem<VocabEntry[]>(
    'local:chineseExtensionVocabList', { fallback: [] },
  ),

  // ---- Session counters ----
  sessionCount: storage.defineItem<number>('local:sessionCount', { fallback: 0 }),
  todayLookupCount: storage.defineItem<number>('local:todayLookupCount', { fallback: 0 }),
  totalLookups: storage.defineItem<number>('local:totalLookups', { fallback: 0 }),
  todayLookups: storage.defineItem<number>('local:todayLookups', { fallback: 0 }),
  lastResetDate: storage.defineItem<string>('local:lastResetDate'),

  // ---- Anki ----
  ankiSettings: storage.defineItem<AnkiSettings>('local:ankiSettings'),
  ankiCardsCreated: storage.defineItem<number>('local:ankiCardsCreated', { fallback: 0 }),
  ankiCardsToday: storage.defineItem<number>('local:ankiCardsToday', { fallback: 0 }),
  ankiSuccessCount: storage.defineItem<number>('local:ankiSuccessCount', { fallback: 0 }),
  ankiTotalAttempts: storage.defineItem<number>('local:ankiTotalAttempts', { fallback: 0 }),
  ankiSuccessRate: storage.defineItem<number>('local:ankiSuccessRate', { fallback: 0 }),
  lastAnkiResetDate: storage.defineItem<string>('local:lastAnkiResetDate'),

  // ---- Video / subtitles ----
  videoFeatureEnabled: storage.defineItem<boolean>('local:videoFeatureEnabled', { fallback: true }),
  videoPlayer: storage.defineItem<VideoPlayerSettings>('local:videoPlayer'),
  subtitleSettings: storage.defineItem<Record<string, any>>('local:subtitleSettings', { fallback: {} }),
  subtitlePreferences: storage.defineItem<SubtitlePreferences>('local:subtitlePreferences', {
    fallback: { global: {}, perVideo: {} },
  }),
  platformSidebarSettings: storage.defineItem<Record<string, any>>(
    'local:platformSidebarSettings', { fallback: {} },
  ),
  /** Legacy single-overlay keys, still read for migration and written on change. */
  subtitlePosition: storage.defineItem<Record<string, any>>('local:subtitlePosition'),
  /** Overlay font size in pixels. */
  subtitleSize: storage.defineItem<number>('local:subtitleSize'),
  subtitleVisibility: storage.defineItem<boolean>('local:subtitleVisibility'),
  /** Legacy, migrated into `videoPlayer` on load. */
  ytSidebarSettings: storage.defineItem<Record<string, any>>('local:ytSidebarSettings'),

  // ---- Shortcuts ----
  shortcuts: storage.defineItem<ShortcutSettings>('local:shortcuts', { fallback: {} }),

  // ---- Onboarding / install metadata ----
  hasCompletedOnboarding: storage.defineItem<boolean>('local:hasCompletedOnboarding', { fallback: false }),
  onboardingCompletedDate: storage.defineItem<string>('local:onboardingCompletedDate'),
  installDate: storage.defineItem<string>('local:installDate'),
  extensionVersion: storage.defineItem<string>('local:extensionVersion'),
  extensionLastUpdateDate: storage.defineItem<string>('local:extensionLastUpdateDate'),

  // ---- Legacy top-level popup hotkeys (superseded by `shortcuts.popup`) ----
  hotkeyMarkUnknown: storage.defineItem<string>('local:hotkeyMarkUnknown'),
  hotkeyMarkIgnored: storage.defineItem<string>('local:hotkeyMarkIgnored'),
  hotkeyMarkKnown: storage.defineItem<string>('local:hotkeyMarkKnown'),
  hotkeyAnkiAdd: storage.defineItem<string>('local:hotkeyAnkiAdd'),
} as const;

/** Per-language recent lookups; the key is built at runtime from a language code. */
export function recentVocabItem(languageCode: string) {
  return storage.defineItem<VocabEntry[]>(`local:recentVocab_${languageCode}`, { fallback: [] });
}

export { storage };
