import './style.css';
import '@/content/components/language-selector/language-selector.css';
// Imported rather than linked from the HTML: an absolute /ui/... href is
// rewritten to a filesystem path by the dev server and 404s, leaving the demo
// popup unstyled during development.
import '@/public/ui/popup/popup.css';

import '@/content/languages/base-language-adapter';
import '@/content/languages/chinese-adapter';
import '@/content/languages/space-separated-adapter';
import '@/content/languages/language-registry';
import '@/content/vocab-manager';
import '@/content/dictionary-bridge';
import '@/content/dictionary-manager';
import '@/content/frequency-manager';
import '@/content/text-highlighter';
import '@/content/page-processor';
import '@/content/pronunciation-manager';
import '@/content/pronunciation';
import '@/content/anki-manager';
import '@/content/popup/components/popup-positioner';
import '@/content/popup/components/popup-content-builder';
import '@/content/popup/components/popup-event-handler';
import '@/content/popup/components/card-navigator';
import '@/content/popup/components/definition-filter';
import '@/content/popup/components/card-manager';
import '@/content/popup/popup-settings-manager';
import '@/content/popup/popup-manager';
import '@/content/popup/multi-card-popup-manager';
import '@/content/utils/activation-controller';
import '@/content/utils/lookup-controller';
import '@/content/components/language-selector/language-selector';
import '@/content/onboarding/first-run-detector';
import '@/content/onboarding/onboarding-controller';
import '@/ui/onboarding/onboarding';

// The floating-character background is generated by OnboardingPage
// (setupFloatingCharacters). onboarding.html also carried an inline <script>
// doing the same thing, which MV3's CSP had always blocked; it is deliberately
// not revived here, since reviving it rendered the glyphs twice.
